# Generated by Django 5.2.8 on 2026-01-02 09:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "cover",
                    models.CharField(
                        choices=[("Hardcover", "Hard"), ("Softcover", "Soft")],
                        default="Hardcover",
                        max_length=15,
                    ),
                ),
                (
                    "inventory",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of copies available in the book_service.",
                    ),
                ),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
